### PR TITLE
Remove extra print statement

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by josegonzalez** [comment]
The alternative to removing this line is to monkey_patch it before calling configure:

```python
import time
from fdtsqlalchemy import SQLADebugPanel
from flask_debugtoolbar import DebugToolbarExtension

def _before_cursor_execute(wrapped_func):
    wrapped_func = wrapped_func.__func__
    def _w(*args, **kwargs):
        SQLADebugPanel._locals()['QUERY_TIMER'] = time.time()
    return classmethod(_w)

SQLADebugPanel._before_cursor_execute = _before_cursor_execute(SQLADebugPanel._before_cursor_execute)

SQLADebugPanel.Configure(flask_app, engine)
DebugToolbarExtension(flask_app)
```

**Comment by eMerzh** [comment]
thanks @josegonzalez , and for others, don't forget to `import time`

**Comment by eMerzh** [comment]
thanks @clavery for the merge :)

**Comment by josegonzalez** [comment]
@clavery can you also make a release on pypi?

**Pull request merged**
